### ISSUE TITLE
Multiple Steam Librarys

### ISSUE THREAD

**Issue by rattailgamer** [odeyity/Playnite-Update-Checker-Plugin#1]
Hey I have multiple Steam librarys on different drives. Is There a way to add multiple?

**Comment by noahdai13** [comment]
Hi there, sorry for the late reply. I have moved away from Playnite, so naturally also from developing this plugin however I do recall developing that feature in a beta. I will take a look over the weekend and see where I got with it.

**Comment by rattailgamer** [comment]
Hey,

Thank you so much if you get the time to check it that would be awsoem.
But I completly get if it doesn't fit since you moved on.

Greetings from Germany
________________________________

**Comment by noahdai13** [comment]
Hey mate, just pushed out <a href="https://github.com/odeyity/Playnite-Update-Checker-Plugin/releases/tag/1.3.0">```Release 1.3.0```</a> which includes this feature. You can now add up to 5 Steam paths which I hope should be enough. Let me know if you have any problems with it and I'll try to help. Thanks :)

**Comment by rattailgamer** [comment]
Thank you so much !!!! :)

**Comment by noahdai13** [comment]
Bitte schön :)

**Comment by rattailgamer** [comment]
oh auch ein Deutscher? 😅

**Comment by noahdai13** [comment]
Haha nein, ich bin kein Deutscher. Ich komme aus England und ich lerne Deutsch in der Schule :)
