### ISSUE TITLE
Add a short tutorial of 3 lines to explain how to configure

### ISSUE THREAD

**Issue by MrLordArcos** [odeyity/Playnite-Update-Checker-Plugin#2]
For my part, I didn't understand why the extension wasn't working, and it was by returning to the GitHub page that I saw that I needed to put a link to the Steam manifest, and I had to quickly search on the internet where to find it to make the extension work. 
I think a very brief 3-line tutorial for less savvy people like me could help.

PS: Sorry for any mistakes, English is not my native language.

**Comment by noahdai13** [comment]
Hi mate, no worries your English is great! I haven’t worked on this plugin for a while but I’ll add something onto the github to make it easier. Is that what you mean?

**Comment by MrLordArcos** [comment]
Yes, exactly, put a tutorial on GitHub or directly in the description on Playnite. I think it could help people like me who are discovering Playnite and transitioning. That would be great.

**Comment by noahdai13** [comment]
Added in the commit 2f7df3a to the github, and requested to add to the plugin description  https://github.com/JosefNemec/PlayniteAddonDatabase/pull/357

**Comment by MrLordArcos** [comment]
It's perfect, thank you very much! I think it will help newcomers like me

**Comment by noahdai13** [comment]
No problem!! :)
