### ISSUE TITLE
Playnite Game Update checker won't run because the extension thinks directory doesn't exist (after switching to portable install)

### ISSUE THREAD

**Issue by mxp83** [odeyity/Playnite-Update-Checker-Plugin#3]
Seems like even after I deleted the config.json and the actual extension I get an error when I try to launch the manifestreader.exe in powershell (the plugin will execute and close immediately). When I manually run in powershell I can see the error spits out:

C:\Playnite\Extensions\UpdateChecker_74fe180c-7038-4908-bec1-94194b73b2e4\manifestreader>manifestreader.exe
Traceback (most recent call last):
File "manifestreader.py", line 8, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\((OLD INSTALL OF PLAYNITE, NOT PORTABLE))\\AppData\\Roaming\\Playnite\\ExtensionsData\\74fe180c-7038-4908-bec1-94194b73b2e4\\config.json'
[38856] Failed to execute script 'manifestreader' due to unhandled exception!

**Comment by noahdai13** [comment]
Not using Playnite much anymore but I'll try and help the best I can

**Comment by noahdai13** [comment]
So is the ExtensionsData located in the portable folder `C:\Playnite`?

**Comment by mxp83** [comment]
Yes it is.  C:\Playnite.

**Comment by noahdai13** [comment]
Should be fixed in https://github.com/odeyity/Playnite-Update-Checker-Plugin/releases/tag/1.3.1 but please let me know if you continue to have issues.

Thanks for creating an issue :)
