### ISSUE TITLE
Can't be installed, addon manifest points to 404

### ISSUE THREAD

**Issue by JosefNemec** [odeyity/Playnite-Update-Checker-Plugin#5]
https://github.com/JosefNemec/PlayniteAddonDatabase/blob/master/addons/generic/odeyity_SteamUpdate.yaml points to 404. Please fix the path, nobody can install this until then.

**Comment by noahdai13** [comment]
Thanks for pointing this out, forgot that changing the branch name would have consequences. Fixed 👍
